### ISSUE TITLE
Using the search function when is already open.

### ISSUE THREAD

**Issue by ClassicSpeed** [JulienKluge/Spedit#14]
If you used the Search function (Ctrl+F) and you want to search something again that you selected, you have to select the new text/word press Ctrl+F to close the search windows and then press Ctrl+F again to auto-paste the new word.

I know that I could just copy-paste the word with the mouse, but It's fastest to just use Ctr+F to autopaste new word.

I'm aware that this could be the way that you want it to function. So it's just a suggestion.

**Comment by JulienKluge** [comment]
Okay so, you have to explain this a little bit more for me. I did not really interstood what you wnated to say :D

**Comment by ClassicSpeed** [comment]
Ok sorry, let's try again.

If you try to search something you select the text, press Ctrl+F and you already have the selected text on the search window, that's perfect.

Now, if you want to search something else, a "new word" while the search box is already open you have to:
1.Select the new word.
2.Press Ctrl+F to close the already opened search box.
3.Press Ctrl+F again to re-open the search box with the new word in it.

So I suggest that if the search box doesn't have the focus (you clicked somewhere else but the box is still open) and you press Ctrl+F, the new selected text should replace the old text on the search box and gain focus again.

I don't know if I explained myself right this time, and I know it's kind of picky what I'm asking for, thanks for this awesome editor!

**Comment by JulienKluge** [comment]
this would be easily possible but imagine following case:
A good guy sp-developer, lets name him greg, is developing a big sp script.
greg defines a global variable 'g_var' as an int and have 1981651 occurences of this variable.
Because greg is not clever, he realize he has to change every occurence of this variable.
He search every occurence and changing it. He search again but he found only another variable named g_varHandle, so he thinks he found everything and wants to close the searchreplace grid and presses ctrl+f. But the editor selected g_var and just replace the old find-pattern and greg gets irritated whats just happened :D 

I really have no clue why I wrote this story xD 
But it shows why we cant implement this ^^ but thanks for the suggestion.
