### ISSUE TITLE
Addition: Specify include directories

### ISSUE THREAD

**Issue by WildCard65** [JulienKluge/Spedit#27]
This would benefit a lot of people to be able to tell SPEdit where to look for includes no matter what configuration is selected(Example: main include dirs hold all the stock SM includes, extra includes include things like: <path to folder>/ff2_includes which holds the includes things like FF2 rely on. SPComp supports this as far as I know of.

**Comment by JulienKluge** [comment]
Spcomp supports that? I mean I'll look into the code but i would highly doubt it. 
You can specify the includes in the script to tell spcomp where it should search but i dont think that the -i switch would support multiple directorys (there's also no syntax defined for that case).
I'll never the less look in the compiler code when i am home. 
The problem is: i could easily implement multiple directories. But as you sad: does spcomp support this?

**Comment by WildCard65** [comment]
I looked in SM's AMBuilder file for the compile process of the sm plugins and found 2 -I switches.
Edit: Did a test run and got the following:  
spcomp ff2_test.sp -ocompile/ff2_test.smx -ipath_to_my_downloads_folder/scripting/include  
ff2_test.sp includes freak_fortress_2.inc which the inc is in path_to_my_downloads_folder/scripting/include  
spcomp said it couldn't find morecolors.inc(freak_fortress_2.inc depends on morecolors.inc)

**Comment by WildCard65** [comment]
To add onto this, probably be best to only supply 1 spcomp.exe(the 1.7 one) and just pass it an -i to appropriate include path.

**Comment by WheteThunger** [comment]
This is certainly a must-have feature and the compiler already supports it with `spcomp.exe -ipath1 -ipath2`. I have needed to use it in several cases, and one person I work with does this all the time to separate core/external includes from his git repo.

**Comment by JulienKluge** [comment]
If the Compiler supports multiple include directorys, and I'll test that too, this will come..in the future..

**Comment by JulienKluge** [comment]
implemented and thanks.
