### ISSUE TITLE
Compiler output

### ISSUE THREAD

**Issue by benjaminforras** [JulienKluge/Spedit#45]
It doesn't shows the compiler's output. ( It doesn't show the errors either )
![Unnamed](https://cloud.githubusercontent.com/assets/10364896/14495834/681dfa78-0191-11e6-9b1d-b2a710f59b36.png)

**Comment by Phil25** [comment]
Shows everything all right for me.

**Comment by benjaminforras** [comment]
I'm using the latest sourcemod compiler.
It doesn't show the compiler's output. Also it always displays 'Done' on the left side below the filename. ( Even if an error occurred )
![Unnamed](https://cloud.githubusercontent.com/assets/10364896/14501046/cc98239e-01a4-11e6-8f7c-8cfd8d0bf01b.png)

**Comment by JulienKluge** [comment]
No output simply means everything compiled succesfully.

**Comment by benjaminforras** [comment]
No becouse, it shows nothing, when I have an error in it.
If I compile it manually it shows the error.
This is what I see after compiling: 
![Unnamed](https://cloud.githubusercontent.com/assets/10364896/14501894/efd2d2b0-01a8-11e6-8840-4010a918c7e4.png)

**Comment by benjaminforras** [comment]
I think the problem is your regex.
I copied your regex code from your source and pasted it to here: https://regex101.com/

Result:
![Unnamed](https://cloud.githubusercontent.com/assets/10364896/14579754/3e3bf3fa-03b6-11e6-9b36-d283d18193e8.png)

**Comment by JulienKluge** [comment]
Well, no x3.
First of all, you copied the regex wrong. the   @"   at the start of your "regex" is not part of the regex. Delete it and it works. Second, you cant expect a regex written with .NET to work with pcre.  Regexes across different platforms can have different properties. Especially since the regex in my programm is called with the multiline option. Also I use the non-greedy operator "+?" which is not available in every regex lib.
Third: Your problem (you are btw. the only on who encounters it out of several thousand users.) lies in the standartouput link between spedit and the compiler. I have only one idea how this could be happen and it's easily checkable. Try to start Spedit with administrator-rights. Test the compiling then. If it works, then I tell you how to change it and perhaps i try to program a warning for this case (also while im not able to tell if this is possible).

**Comment by benjaminforras** [comment]
You're right.
I tested your regex and it works (on this site: http://regexstorm.net/tester ), but I don't know why it's not showing it in your program. ( I tried with administrator-rights, still not working. )
I'll reinstall it, I hope it works after.

**Comment by benjaminforras** [comment]
After reinstalling it works like a charm

**Comment by JulienKluge** [comment]
Lol, happy use and thanks for using spedit ^^ 
closed.
