### ISSUE TITLE
More color options & parsed methods intellisense

### ISSUE THREAD

**Issue by meev** [JulienKluge/Spedit#46]
![nogawe9](https://cloud.githubusercontent.com/assets/5840880/14512671/64c6bb44-01e1-11e6-9f37-edd5b8d0aca4.png)
The `file.Close()` doesn't color itself correctly
#### Add the following color thingies to the color editor:
- Variables (completly white text)
- On focus window frame (completly red frame around the window when active/focus)
- The color of a functions variable name `stock void afunction(int thistext) { .. }`
- A new option for enum colors
- Marked text color
#### Parse these things inside methodmaps in include files:

```
// Resizes an array.  If the size is smaller than the current size, the
// array is truncated.
//
// @param newsize       New size.
```
#### Heres a few suggestions & bugs:
- Dynamically figure out self defined functions so they come up as suggestions in the intellisense
- An option in the color editor to put hex codes instead of having to do the sliders on all of them
- Either something that dynamically figures out when you make new parsed constants or a button where you can refresh so it will color the parsed constants correctly, instead of having to restart the program for the colors to be there
- Making a parsed constant in a *.sp file will not color them no matter what you do
- Having another default color scope that is more appealing to the eye, I personally prefer & copied most of the colors from visual studio dark theme into the spedit, if you want my options file let me know!

**Comment by JulienKluge** [comment]
Wow, okay. I like your colors. But from the beginning.
- Variables arent parsed. Therefore there cannot be a color for it.
- Already implemented it. I will push the commit it soon.
- This is implemented if I got you right.
- Why enum colors?
  -sounds good. I'll do that.

This should be already parsed. It must be one line above the method. It's only, that the intellisense currently cannot display informations from methods.
- This is implemented for all opened *.inc-files.
- Year but not that important.
- I already thought about it. It's planned. 
- Because *.sp Files don't get parsed. I would like to continue this behaviour out of several reasons.

I really like the colors in your picture. I would be glad if you would work out a new color-sheme. I'll implement that into the next version.

**Comment by JulienKluge** [comment]
If you would be ready to make the color-sheme, i would send you a pre-version, where you can switch Theme from Dark to Ligh and switch App-Colors to match this.

**Comment by meev** [comment]
> I really like the colors in your picture. I would be glad if you would work out a new color-sheme. I'll implement that into the next version. 

Sure I can do that, what do I need to do exactly?

> Variables arent parsed. Therefore there cannot be a color for it.

A color option for non parsed text could be an option then

> This is implemented if I got you right.

![lwu89at](https://cloud.githubusercontent.com/assets/5840880/14535773/c2a7cefe-026f-11e6-9e00-7b0c1524ca27.png)
the marked text here is what I ment (forgot all of the "client" ones)

**Comment by JulienKluge** [comment]
Do you have an e-mail to communicate for?

**Comment by meev** [comment]
I would prefer using steam: steamcommunity.com/id/mevv

**Comment by Bara** [comment]
![spedit](https://cloud.githubusercontent.com/assets/17928280/16179653/f07ef53e-366b-11e6-90e8-b93e7793de3a.png)

**Comment by JulienKluge** [comment]
this shouldn't be happening and it doesn't happen in the original distributed program. Atleast not on my test-machines.
