### ISSUE TITLE
There is a memory leak Spedit process (close, don't save).

### ISSUE THREAD

**Issue by DarklSide** [JulienKluge/Spedit#74]
If you close an edited file without saving it in front of him.

**Comment by WildCard65** [comment]
C# shouldn't physically allow memory leakage to last after program execution due to GC.

**Comment by DarklSide** [comment]
It is understood that the process Spedit - every second increases memory in the range of 0.05-0.10 MB.
And the interface is tightly hangs.

**Comment by JulienKluge** [comment]
I doubt that there is a memory leak but i'll test it. 
I propose another possibility for your observation: SPEdit ist optimized for multithreaded execution. Beside the main UI Thread there are several other Threads running in the background like Parsing your includes, analyze your current code, updating foldings, etc. . The Garbage which is produced in the process of doing so is not automaticly deleted. Its the GC which firstly only collects old unreferenced objects and later kills them. The GC itself runs in a background thread. It uses times of low CPU consumption to look through the ram and delete objects. If you have a low-tier CPU, the mainthread could use up so many ressources, that it pressures the GC to run very rarely which leads to a longer build up of garbage over time. If this is the case, than i can simply do almost nothing against it since the majority of cpu-power is consumed by the wpf-visuals i have no control over. This could be exponentially worse if you dont have a installed (or at least used) graphics card. This would also explain your "lagging ui" btw.
